AM_CFLAGS+=-g -O2
AM_CXXFLAGS+=-g -O2
#AM_CPPFLAGS+=$(BOOST_CPPFLAGS)

AM_CFLAGS+=$(if $(DEBUG), -g -O0 -D_DEBUG)
AM_CXXFLAGS+=$(if $(DEBUG), -g -O0 -D_DEBUG)

AM_CPPFLAGS+=$(if $(OPTIMIZE), -DNDEBUG)
AM_CFLAGS+=$(if $(OPTIMIZE), -O3)
AM_CXXFLAGS+=$(if $(OPTIMIZE), -O3)

AM_CFLAGS+=$(if $(PROFILE), -pg)
AM_CXXFLAGS+=$(if $(PROFILE), -pg)
